# Generated by Django 3.0.7 on 2020-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docscanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_outline', models.ImageField(upload_to='test_images/outline_imgs')),
                ('scanned_image', models.ImageField(upload_to='test_images/scanned_imgs')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_image',
            field=models.ImageField(upload_to='users/documents/'),
        ),
    ]
