# Generated by Django 3.0.7 on 2020-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docscanner', '0004_auto_20200614_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='outline_image',
            field=models.ImageField(null=True, upload_to='users/temp/outlineimages/'),
        ),
    ]
