# Generated by Django 3.0.7 on 2020-06-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docscanner', '0005_document_outline_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentImage',
        ),
    ]
